cat Chloe.xyzb > all.xyzb
cat Ripley.xyzb >> all.xyzb
cat Abby.xyzb >> all.xyzb
cat BenBob.xyzb >> all.xyzb
cat Ibeth.xyzb >> all.xyzb
cat Judy.xyzb >> all.xyzb
cat Olga.xyzb >> all.xyzb
cat Bonnie.xyzb >> all.xyzb
cat Mimi.xyzb >> all.xyzb
cat Merk.xyzb >> all.xyzb
cat Ellie.xyzb >> all.xyzb
cat Ornette.xyzb >> all.xyzb
cat Gillian.xyzb >> all.xyzb
cat Clementina.xyzb >> all.xyzb
cat Atlas.xyzb >> all.xyzb
cat Sofie.xyzb >> all.xyzb
cat Pliny.xyzb >> all.xyzb
cat Greg.xyzb >> all.xyzb
cat Veruca.xyzb >> all.xyzb
cat Kyle.xyzb >> all.xyzb
cat Chibi.xyzb >> all.xyzb