cat Veruca.txt > all.txt
cat Chibi.txt >> all.txt
cat Abby.txt >> all.txt
cat BenBob.txt >> all.txt
cat Bonnie.txt >> all.txt
cat Chloe.txt >> all.txt
cat Clementina.txt >> all.txt
cat Ellie.txt >> all.txt
cat Gillian.txt >> all.txt
cat Ornette.txt >> all.txt
cat Pliny.txt >> all.txt
cat Ripley.txt >> all.txt
cat Sofie.txt >> all.txt
cat Greg.txt >> all.txt
cat Ibeth.txt >> all.txt
cat Olga.txt >> all.txt
cat Mimi.txt >> all.txt
cat Kyle.txt >> all.txt
cat Atlas.txt >> all.txt
cat Judy.txt >> all.txt
cat Merk.txt >> all.txt